# Generated by Django 5.1.7 on 2025-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_friend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='group_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
